services:
  - docker

before_install:
  - docker build -t yacchin1205/research-notebook .

script:
  - docker run yacchin1205/research-notebook papermill /home/jovyan/sample-notebooks/00_Tools.ipynb /tmp/Result.ipynb
